name: Reset caches

runs:
  using: 'composite'
  steps:
    - name: Reset caches
      uses: actions/github-script@v9
      with:
        script: |
          const { owner, repo } = context.repo;
          const { data: caches } = await github.rest.actions.getActionsCacheList({
            owner,
            repo,
          });

          for (const cache of caches) {
            try {
              await github.rest.actions.deleteActionsCacheById({
                  owner,
                  repo,
                  cache_id: cache.id,
              });
              console.log(`Deleted cache ${cache.id} (${cache.key})`);
            } catch (e) {
              console.error(`Failed to delete cache ${cache.id} (${cache.key})`);
              console.error(e);
            }
          }
