name: Backport
description: Backports commits to given target branches

on:
  workflow_call:

jobs:
  selection:
    runs-on: ubuntu-slim
    outputs:
      branches: ${{ steps.branch_selection.outputs.result }}
    steps:
      - uses: actions/github-script@v9
        id: branch_selection
        env:
          LABELS: ${{ join(github.event.pull_request.labels.*.name, '◬') }}
        with:
          result-encoding: string
          script: |
            return JSON.stringify(process.env.LABELS.split('◬').filter((l) => l.startsWith('target:')));

  backport:
    runs-on: ubuntu-slim
    outputs:
      failed_branches: ${{ steps.update_failed_branches.outputs.failed_branches }}
    strategy:
      matrix:
        label: ${{ fromJSON(needs.selection.outputs.branches) }}

    steps:
      - name: Create GitHub App token
        id: token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PEM }}
      - name: Get branch name from label
        id: branch_name
        run: |
          echo "branch=$(echo ${{ matrix.label }} | sed -n 's/target: \([0-9]*.x\).*/\1/p')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v7
        if: steps.branch_name.outputs.branch
        with:
          token: ${{ steps.token.outputs.token }}
          fetch-depth: 0

      - name: Cherry-pick changes into ${{ steps.branch_name.outputs.branch }}
        if: steps.branch_name.outputs.branch
        run: |
          git checkout ${{ steps.branch_name.outputs.branch }}
          git -c user.name="github-actions" -c user.email="github-actions@github.com" cherry-pick ${{ github.sha }}
          git push

      - name: Update failed branches
        if: ${{ failure() }}
        id: update_failed_branches
        run: |
          echo "failed_branches=$(echo ${{ steps.branch_name.outputs.branch }} ${{ steps.update_failed_branches.outputs.failed_branches}})" >> $GITHUB_OUTPUT

  report:
    runs-on: ubuntu-slim
    needs: backport
    if: always() && needs.backport.result == 'failure' &&
      github.event.pull_request.user.login != 'renovate[bot]' &&
      needs.backport.outputs.failed_branches

    steps:
      - uses: actions/github-script@v9
        env:
          BRANCHES: ${{ needs.backport.outputs.failed_branches }}
        with:
          script: |
            const body = `
              ⚠ Could not backport pull request into ${process.env.BRANCHES}!
              Please manually backport the change via git cherry pick.
              [ ] Completed
            `;
            github.rest.issues.createComment({
              issue_number: github.event.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
