name: Pull Request Labelling
description: Add or remove target labels to pull request

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  labelling:
    runs-on: ubuntu-slim
    if: github.event.pull_request.user.login != 'renovate[bot]'
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/github-script@v9
        id: target-label
        with:
          result-encoding: string
          script: |
            const { data: branches } = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo,
              protected: true,
            });
            return branches.map((b) => b.name).filter((b) => b.endsWith('.x')).map((b) => parseInt(b.split('.')[0])).sort().at(-1);
      - name: Add target label
        if: "${{ !contains(github.event.pull_request.body, 'BREAKING CHANGE:') && !contains(github.event.pull_request.labels.*.name, 'target: major') }}"
        run: gh issue edit $PR_NUMBER --repo ${{ github.repository }} --add-label "target: ${{ steps.target-label.outputs.result }}"
      - name: Remove target label
        if: "${{ contains(github.event.pull_request.body, 'BREAKING CHANGE:') || contains(github.event.pull_request.labels.*.name, 'target: major') }}"
        run: gh issue edit $PR_NUMBER --repo ${{ github.repository }} --remove-label "target: ${{ steps.target-label.outputs.result }}"
